# Generated by Django 3.1.1 on 2020-09-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=300, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ApiArticle',
                'verbose_name_plural': 'ApiArticles',
            },
        ),
        migrations.CreateModel(
            name='MyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=300, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MyArticle',
                'verbose_name_plural': 'MyArticles',
            },
        ),
        migrations.CreateModel(
            name='AllArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
